library(xlsx)
cars<-read_xlsx("Car Performance Comparision_Problem.xlsx",sheet = "p2")
car<-c(rep("Car-4",10),rep("Car-5",10),rep("Car-6",10))
performance<-c(cars$`Car-4`,cars$`Car-5`,cars$`Car-6`)
df<-data.frame(car,performance)
plot(performance~car,data=df)
cars.aov<-aov(performance~car,data=df)
summary(cars.aov)
myanova <- anova(cars.aov)
cbind(myanova, 'CriticalValue' = qf(1-.05, myanova[1,1], myanova[2,1]))