library(xlsx)
cars<-read_xlsx("Car Performance Comparision_Problem.xlsx",sheet = "p1")
car<-c(rep("Car-1",10),rep("Car-2",10),rep("Car-3",10))
performance<-c(cars$`Car-1`,cars$`Car-2`,cars$`Car-3`)
df<-data.frame(car,performance)
plot(performance~car,data=df)
cars.aov<-aov(performance~car,data=df)
summary(cars.aov)
myanova <- anova(cars.aov)
cbind(myanova, 'CriticalValue' = qf(1-.05, myanova[1,1], myanova[2,1]))
